import NavButtons from "@/components/NavButtons";
import Steps from "@/components/Steps";
// import "./globals.css";
import { Montserrat } from "next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {

	return (
		<html lang="en">
			<body className={inter.className}>
				<Steps />
				{children}
                <NavButtons />
			</body>
		</html>
	);
}
